# This workflow builds a Maven multi-module project and uploads each generated JAR file as a separate artifact.
# It can be triggered by a push to the main branch, the creation of a release, or an external repository_dispatch event.

name: CrayonSystem

on:
  push:
    branches:
      - main
  release:
    types: [created]
  repository_dispatch:
    types: [manual-trigger]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Find and upload all JARs individually
        run: |
          find . -type f -name "*.jar" | while read jar; do
            name=$(basename "$jar")
            echo "Uploading $jar as artifact: $name"
            gh_action_output_name="${name//[^a-zA-Z0-9_-]/_}" # Clean name
            echo "::group::Upload $name"
            gh_output_path=$(dirname "$jar")/$name
            echo "Upload path: $gh_output_path"
            gh_action_artifact_name="${name%.*}" # Without .jar
            gh_action_artifact_name="${gh_action_artifact_name//[^a-zA-Z0-9_-]/_}"
            tar -czf "${gh_action_artifact_name}.tar.gz" -C "$(dirname "$jar")" "$(basename "$jar")"
            gh_action_artifact_path="${gh_action_artifact_name}.tar.gz"
            echo "Final artifact: $gh_action_artifact_path"
            gh_action_artifact_name="${gh_action_artifact_name}_artifact"
            echo "::endgroup::"

            # Upload as individual artifact
            gh_api_upload_cmd="actions/upload-artifact@v4"
            echo "Uploading $gh_action_artifact_path as $gh_action_artifact_name"
            echo "::group::GitHub Upload $gh_action_artifact_name"
            echo "::endgroup::"
            echo "::notice file=$jar::Uploading $jar as $gh_action_artifact_name"
            mkdir -p "upload_temp"
            cp "$jar" "upload_temp/$name"
            gh_action_artifact_name="${gh_action_artifact_name//[^a-zA-Z0-9_-]/_}"
            gh_action_artifact_name="${gh_action_artifact_name:-jar}"
            echo "::notice ::Uploading: $gh_action_artifact_name"
            echo "::group::Upload Artifact $gh_action_artifact_name"
            gh_action_upload_cmd="gh_action_upload_$gh_action_artifact_name"
            echo "::endgroup::"

            # Upload using action
            tarball="${name}.tar.gz"
            echo "::notice ::Uploading $jar as $name"
            tar -czf "$tarball" -C "$(dirname "$jar")" "$(basename "$jar")"
            echo "::notice ::Uploading $tarball"
          done
        shell: bash

      - name: Upload artifacts separately
        uses: actions/upload-artifact@v4
        with:
          name: all-jars
          path: '**/target/*.jar'
