# This workflow builds a Maven multi-module project and uploads each generated JAR file as a separate artifact.
# It can be triggered by a push to the main branch, the creation of a release, or an external repository_dispatch event.

name: CrayonSystem

on:
  push:
    branches:
      - main
  release:
    types: [created]
  repository_dispatch:
    types: [manual-trigger]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Find all JAR files
        id: find_jars
        run: |
          echo "jar_files<<EOF" >> $GITHUB_OUTPUT
          find . -type f -name "*.jar" -print >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload each JAR separately
        run: |
          echo "${{ steps.find_jars.outputs.jar_files }}" | while read jar; do
            if [ -f "$jar" ]; then
              artifact_name=$(basename "$jar")
              echo "Uploading $jar as $artifact_name"
              gh release upload "$GITHUB_REF_NAME" "$jar" --clobber
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
